// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4W7RU5rut7PfmRtIj6q0j4Ysws03uoyc',
    appId: '1:570786529381:web:577867a844b41da2b5068c',
    messagingSenderId: '570786529381',
    projectId: 'thaicare-d2318',
    authDomain: 'thaicare-d2318.firebaseapp.com',
    storageBucket: 'thaicare-d2318.firebasestorage.app',
    measurementId: 'G-2QB00P74PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYnC-N6olhNDOs_vf8XvFjgq082ACa0k',
    appId: '1:570786529381:android:0a9ada27e44ee3a8b5068c',
    messagingSenderId: '570786529381',
    projectId: 'thaicare-d2318',
    storageBucket: 'thaicare-d2318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIjLPCpwkRNEfW64XWCJKNC0T877FlDVU',
    appId: '1:570786529381:ios:d21445d040e8b04ab5068c',
    messagingSenderId: '570786529381',
    projectId: 'thaicare-d2318',
    storageBucket: 'thaicare-d2318.firebasestorage.app',
    iosClientId: '570786529381-qmev2dutrg6ebk7fvnc8iskp86hejr0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.thaicare',
  );

}